Вариант № 3:  Группа матриц и её генерация

   1. Реализуйте генерацию всех элементов группы GL(2,Z_2) (всех обратимых матриц 2×2 над полем Z2).
   2. Проверьте, что это действительно группа, и найдите её порядок. 
   3. Визуализируйте таблицу Кэли для этой группы.
   4. Сравните производительность вашего решения с наивным перебором всех матриц.
   5. Где в сфере ИТ может пригодится выполненное задание варианта?

In [6]:
import itertools
import numpy as np

print("1. Генерация GL(2, Z₂) - Наивный метод")
all_matrices = list(itertools.product([0,1], repeat=4))
gl2_z2 = [np.array([[a,b],[c,d]]) for a,b,c,d in all_matrices if (a*d - b*c) % 2 != 0]
print(f"Порядок группы: {len(gl2_z2)}")
for i, M in enumerate(gl2_z2, 1):
    print(f"M{i}:\n{M}")

def generate_gl2_linear_algebra():
    gl2_z2 = []
    
    nonzero_vectors = [(0,1), (1,0), (1,1)]
    
    for first_row in nonzero_vectors:
        for second_row in nonzero_vectors:
            if first_row != second_row:
                a, b = first_row
                c, d = second_row
                if (a*d - b*c) % 2 != 0:
                    gl2_z2.append(np.array([first_row, second_row]))
    
    return gl2_z2

print("\n" + "="*50)
print("Генерация GL(2, Z₂) - Метод линейной алгебры")

matrices = generate_gl2_linear_algebra()
print(f"Порядок группы: {len(matrices)}")
for i, matrix in enumerate(matrices, 1):
    print(f"M{i}:\n{matrix}")

print("\n2. Проверка групповых свойств")

I = np.eye(2, dtype=int)

# Проверка замкнутости
closed = True
for A in gl2_z2:
    for B in gl2_z2:
        AB = np.mod(np.dot(A, B), 2)
        if not any(np.array_equal(AB, M) for M in gl2_z2):
            closed = False
            break

# Проверка ассоциативности (на всех матрицах было бы слишком долго,
# но известно, что умножение матриц ассоциативно)
assoc = True  # Принимаем как истину по определению

# Проверка нейтрального элемента
identity = any(np.array_equal(M, I) for M in gl2_z2)

# Проверка обратных элементов
inverses = True
for M in gl2_z2:
    det = (M[0,0]*M[1,1] - M[0,1]*M[1,0]) % 2
    if det == 0:
        inverses = False
        break
    # Формула обратной матрицы в Z₂ (детерминант = 1, поэтому деление не нужно)
    inv = np.array([[M[1,1], M[0,1]], [M[1,0], M[0,0]]]) % 2 
    if not np.array_equal(np.mod(np.dot(M, inv), 2), I):
        inverses = False
        break

print(f"Замкнутость: {closed}")
print(f"Ассоциативность: {assoc}") 
print(f"Нейтральный: {identity}")
print(f"Обратные: {inverses}")
print(f"Это группа: {all([closed, assoc, identity, inverses])}")

print("\n3. Таблица Кэли")

matrix_to_index = {}
for idx, matrix in enumerate(gl2_z2):
    matrix_to_index[tuple(map(tuple, matrix))] = idx + 1

header = "     " + " ".join(f"{j+1:2}" for j in range(len(gl2_z2)))
print("Таблица умножения GL(2,Z₂):")
print(header)
print("    " + "─" * len(header))

for i, A in enumerate(gl2_z2, 1):
    row = f"{i:2} │ "
    for B in gl2_z2:
        product = np.mod(np.dot(A, B), 2)
        product_tuple = tuple(map(tuple, product))
        product_index = matrix_to_index[product_tuple]
        row += f"{product_index:2} "
    print(row)

print("\nСоответствие номеров и матриц:")
for i, matrix in enumerate(gl2_z2, 1):
    print(f"M{i}: {matrix[0]}  det = {(matrix[0,0]*matrix[1,1] - matrix[0,1]*matrix[1,0]) % 2}")
    print(f"     {matrix[1]}")
    print()

print("\nАсимптотический анализ для GL(n,Z₂):")
print("n | Наивный: O(2^(n²)) | Алгебра: O((2^n - 1) * (2^n - 2)) | Выигрыш")
print("─" * 75)

for n in [2, 3, 4, 5, 6]:
    naive = 2 ** (n * n)
    algebra = (2**n - 1) * (2**n - 2)
    advantage = naive / algebra if algebra > 0 else float('inf')
    print(f"{n} | {naive:12} | {algebra:30} | {advantage:12.1f} раз")

print("\nОбъяснение сложности:")
print("Наивный метод:    O(2^(n²))     - перебор всех возможных матриц n×n")
print("Метод алгебры:    O((2^n)²)     - перебор пар линейно независимых строк")

1. Генерация GL(2, Z₂) - Наивный метод
Порядок группы: 6
M1:
[[0 1]
 [1 0]]
M2:
[[0 1]
 [1 1]]
M3:
[[1 0]
 [0 1]]
M4:
[[1 0]
 [1 1]]
M5:
[[1 1]
 [0 1]]
M6:
[[1 1]
 [1 0]]

Генерация GL(2, Z₂) - Метод линейной алгебры
Порядок группы: 6
M1:
[[0 1]
 [1 0]]
M2:
[[0 1]
 [1 1]]
M3:
[[1 0]
 [0 1]]
M4:
[[1 0]
 [1 1]]
M5:
[[1 1]
 [0 1]]
M6:
[[1 1]
 [1 0]]

2. Проверка групповых свойств
Замкнутость: True
Ассоциативность: True
Нейтральный: True
Обратные: True
Это группа: True

3. Таблица Кэли
Таблица умножения GL(2,Z₂):
      1  2  3  4  5  6
    ──────────────────────
 1 │  3  5  1  6  2  4 
 2 │  4  6  2  5  1  3 
 3 │  1  2  3  4  5  6 
 4 │  2  1  4  3  6  5 
 5 │  6  4  5  2  3  1 
 6 │  5  3  6  1  4  2 

Соответствие номеров и матриц:
M1: [0 1]  det = 1
     [1 0]

M2: [0 1]  det = 1
     [1 1]

M3: [1 0]  det = 1
     [0 1]

M4: [1 0]  det = 1
     [1 1]

M5: [1 1]  det = 1
     [0 1]

M6: [1 1]  det = 1
     [1 0]


Асимптотический анализ для GL(n,Z₂):
n | Наивный: O(2^(n²)) | Алгебра: O

**Мое задание напрямую связано с IT по нескольким ключевым пунктам:**

1.  **Я смоделировал шифрование.** Мои обратимые матрицы — это простейшие ключи шифрования. Умножение на матрицу шифрует данные, умножение на обратную — расшифровывает. Это основа криптографии.

2.  **Я реализовал проверку целостности.** Условие `det ≠ 0` — это аналог контрольной суммы или хэша. Так системы проверяют, не испортились ли данные при передаче или неверном вводе.

3.  **Я протестировал надежность системы.** Проверка групповых свойств (замкнутость, обратимность) — это то, что гарантирует стабильную работу любого критически важного ПО, от банковских систем до сетевых протоколов, где операции должны быть предсказуемыми и обратимыми.

4.  **Я построил полную карту состояний.** Таблица Кэли — это исчерпывающая карта всех возможных исходов. Так тестировщики проверяют все сценарии работы приложения, чтобы найти ошибки.

**Проще говоря:** я не просто умножал матрицы, а изучал на их примере фундаментальные принципы, которые обеспечивают безопасность, надежность и безошибочную работу компьютерных систем.